### ISSUE TITLE
Проверка адекватности синтаксиса

### ISSUE THREAD

**Issue by jegorpopow** [jegorpopow/EBNF#1]
Посмотрите, сможете ли написать парсер [этого](https://github.com/jegorpopow/EBNF/blob/main/syntax_description.md). По идее разбиение на блоки парсится руками, 
а остальное - не сложнее, чем просто арифметические выражения с несколькими вилами скобок

**Comment by Taifin** [comment]
На первый взгляд всё ок, не понял только про экранирование `\\` (видимо `\`?)

> Нетерминалы представляется как его имя в угловых скобочках, при этом разрешено экранирование символов
`>` и `\\`. Имя нетерминала - произвольный набор ASCII - символов

**Comment by jegorpopow** [comment]
> На первый взгляд всё ок, не понял только про экранирование `\\` (видимо `\`?)
> 
> > Нетерминалы представляется как его имя в угловых скобочках, при этом разрешено экранирование символов
> > `>` и `\\`. Имя нетерминала - произвольный набор ASCII - символов

Там markdown заупрямился, конечно речь про `\`

**Comment by Taifin** [comment]
А ещё в двух местах в примерах видимо потерялись угловые скобки у нетерминалов?

https://github.com/jegorpopow/EBNF/blob/c5be80b3c9aa8c744659cdc0060f66ce7107fb36/syntax_description.md?plain=1#L111

https://github.com/jegorpopow/EBNF/blob/c5be80b3c9aa8c744659cdc0060f66ce7107fb36/syntax_description.md?plain=1#L136
